language: python
sudo: false
python:
- '2.7'
before_install:
- pip install codecov
- pip install -U pip
install: pip install tox
script:
- tox
after_success:
- codecov
deploy:
  provider: pypi
  user: dbryant4
  server: https://pypi.python.org/pypi
  distributions: sdist
  password:
    secure: mF8+G8bquQqmWdXBn45RotzAVfK/lqp2pL6OBSdHDp/jVhHCpr7Wa6DAu4fAB1M41S/Wzc3U3IagJ93hEQ3cQYrAMWfPm1RVVP4F4AH+zxSGsGVZoF7LI+bUK2Mf4/bfn7acVrLy94efVgWg11QWqVzIw1ISPz0z0txngpPfsbk=
  on:
    tags: true
    repo: dbryant4/furtive
