language: python
sudo: false
python:
- '2.7'
before_install:
- pip install codecov
- pip install -U pip
install: pip install tox
script:
- tox
after_success:
- codecov
deploy:
  provider: pypi
  user: dbryant4
  password:
    secure: eedcpTUbEvI0LO63iTSHKb1/hqYqLGQroLgbFiIeHGte3Z999vT9SE7m8GzabgJxh6d7OG2UBAnIfRc62PyuliD6qDc5oBWQz8fgbfsbK0QP8MQaXBwUebvj/zv5WGmMGXee8k12KyYtAplEc52NcTu1TaZE3iJRmW12e6k9Irk=
  on:
    tags: true
    repo: dbryant4/furtive
