language: python
sudo: false
python:
- '2.7'
before_install:
- pip install codecov
install: pip install tox
script:
- tox
after_success:
- codecov
deploy:
  provider: pypi
  user: dbryant4@gmail.com
  server: https://testpypi.python.org/pypi
  password:
    secure: bOcu5tnHlag84/sV6lchV24XCOVh+i7tk73aLtEChpL0U99MbJSrEpvG+VnOBPEsusePZEgaPC0rcdsXKRb8GiTCidNvthBE9wSc9jDZyf1sDVx3VVd4vwpms99EEo9q79FL2llImG8mDghg9bTpDndgoJvynv3Lwl7Eo7BofsM=
  on:
    tags: true
    repo: dbryant4/furtive
