language: python
sudo: false
python:
- '2.7'
- '3.5'
before_install:
- pip install codecov
- pip install -U pip
install: pip install tox
script:
- tox
after_success:
- codecov
deploy:
  provider: pypi
  user: dbryant4
  password:
    secure: MUmIiUotjPFgiiqXgUMBE0pWVcp11TOh5sa9eK9iIcCt9kbl2OKeeJSL4esGEPqxj5Wdgr3nqnvUAMyElj5/FPQuaxzNZ4LxPGoJBC06SiFUIEngrRE7oP51Loq2RMtTLg5v2XDC4BIen8oxvhxRe2OqJwLtLDsciGD6GOSzcdc=
  on:
    tags: true
    repo: dbryant4/furtive
