language: python
sudo: false
python:
- '2.7'
before_install:
- pip install codecov
- pip install -U pip
install: pip install tox
script:
- tox
after_success:
- codecov
deploy:
  provider: pypi
  user: dbryant4
  password:
    secure: lPxj7XGdR8nvSQrDiJJvIq0sz1NajbJdjU/XwqTXD9JLYvQ+JJkaJqoWiakLqXNDP+3yqKMMoKg9PPuNbfS0bevjqmoYTy2rrWIRhFQSSI5XQc2AG1j61scL+GDqg9nKJAWYbdAyklb+ZZv1knHKI8kLfQmLVAhZm27LQj1NuNY=
  on:
    tags: true
    repo: dbryant4/furtive
